# Generated by Django 5.2.1 on 2025-05-21 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria_fotografia_data_fotografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IATool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('GPT', 'gpt'), ('VIDEOS', 'vídeos'), ('IMAGENS', 'imagens'), ('AUDIOS', 'áudios')], default='', max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.ImageField(blank=True, upload_to='iatools/icones/%Y/%m/%d/')),
                ('publicada', models.BooleanField(default=False)),
                ('data_publicacao', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Fotografia',
        ),
    ]
